server {
    listen 3000;
    server_name localhost;
    root /app/data;
    index index.html;

    # Gzip сжатие для улучшения производительности
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

    # Редирект для тайлов
    location ~ ^/osm_tiles/(\d+)/(\d+)/(\d+)\.png$ {
        # Резолвер для Docker
        ### resolver 8.8.8.8 8.8.4.4 valid=300s;
        resolver 1.1.1.1 ipv6=off;

        # Прокси на HTTPS (исправлено!)
        proxy_pass https://tile.openstreetmap.org/$1/$2/$3.png;

        # Только самые необходимые заголовки
        proxy_set_header Host tile.openstreetmap.org;
        proxy_set_header User-Agent "Ekbmap Nginx Cache (root@it-college.ru)";

        # SSL
        proxy_ssl_server_name on;
        proxy_ssl_name tile.openstreetmap.org;

        # Важно! Запрещаем nginx изменять редиректы
        proxy_redirect off;

        # Добавим заголовок для отладки
        add_header X-Proxy "clean-config" always;

    }

    # Для файлов с хешами в имени (обычно создаются при сборке) - добавляем долгий кэш
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff2?|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Для всех остальных запросов - отдаём index.html
    location / {
        try_files $uri $uri/ /index.html;

        # Заголовки для SPA
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Опционально: если нужны логи
    access_log /var/log/nginx/app-access.log;
    error_log /var/log/nginx/app-error.log;
}
