#!/bin/bash

# ai-reminder.sh
# Quick reminder script for AI assistants working on Maps.ai project

echo "🤖 AI Assistant Quick Reference - Maps.ai Project"
echo "=================================================="
echo ""
echo "📚 ESSENTIAL FILES TO READ AT SESSION START:"
echo "--------------------------------------------"
echo "1. AGENTS.md                    - Project overview and structure"
echo "2. docs/guides/author_preferences.md - Development preferences"
echo "3. AI_ASSISTANT_NOTES.md        - Quick reference (this info)"
echo "4. docs/tmp/summary.md          - Current project status"
echo ""
echo "🚀 AI ASSISTANT COMMANDS (NOT SYSTEM COMMANDS):"
echo "-----------------------------------------------"
echo ""
echo "🔹 git-commit - AI workflow for analyzing changes and committing:"
echo "   1. Check git status: git --no-pager status"
echo "   2. Analyze changes: git --no-pager diff --stat"
echo "   3. Create meaningful commit message in English"
echo "   4. Stage all changes: git add ."
echo "   5. Commit: git commit -m \"Title\" -m \"Description\""
echo "   6. Verify: git --no-pager log --oneline -3"
echo ""
echo "🔹 git-push - AI workflow for commit and push:"
echo "   1. Check for changes: git --no-pager status"
echo "   2. If changes exist, run git-commit workflow"
echo "   3. Check commits ready: git --no-pager log --oneline origin/master..HEAD"
echo "   4. Push commits: git push origin master"
echo "   5. Provide status report"
echo ""
echo "🔧 REAL SYSTEM COMMANDS:"
echo "------------------------"
echo "🔹 run-stage - Build pipeline: python3 scripts/commands/run-stage.py [import|buildings|backend|all]"
echo ""
echo "⚡ QUICK REMINDERS:"
echo "------------------"
echo "• git --no-pager [command] - ALWAYS use --no-pager flag"
echo "• pnpm not npm - Use pnpm for package management"
echo "• Named exports only - No default exports"
echo "• Props interface - Simple name for single-component files"
echo "• No React.FC - Let TypeScript infer return types"
echo "• Redux slices - Use slice.selectors and slice.actions"
echo ""
echo "📁 CURRENT CONTEXT:"
echo "-------------------"
echo "• Working on: Camera alignment system"
echo "• Current focus: TopCameraController.tsx"
echo "• Phase: Phase 2 - TopCameraController enhancement"
echo "• Key files: alignmentSlice.ts, AlignmentUI.tsx"
echo ""
echo "💡 TIP: Run this script anytime with: ./scripts/ai-reminder.sh"
echo ""
