#!/bin/bash

# git-commit-helper.sh
# Helper script to remind AI assistant about git-commit workflow

echo "🚀 git-commit workflow reminder for AI assistant"
echo "=================================================="
echo ""
echo "When user says 'git-commit', you should:"
echo ""
echo "1. 📊 Check git status:"
echo "   git --no-pager status"
echo ""
echo "2. 🔍 Analyze changes:"
echo "   git --no-pager diff --stat"
echo "   git --no-pager diff --no-ext-diff <changed_files>"
echo ""
echo "3. 📝 Create meaningful commit message in English that explains:"
echo "   - What was changed"
echo "   - Why it was changed"
echo "   - Technical details if relevant"
echo ""
echo "4. 📦 Stage all changes:"
echo "   git add ."
echo ""
echo "5. 💾 Commit with descriptive message:"
echo "   git commit -m \"Title\" -m \"Detailed description\""
echo ""
echo "6. ✅ Verify commit:"
echo "   git --no-pager log --oneline -3"
echo ""
echo "Example commit structure:"
echo "-------------------------"
echo "Add model rotation controls to TopCameraController"
echo ""
echo "- Implement Ctrl+A/D for Y-axis model rotation"
echo "- Add Ctrl+↑/↓ for rotation step adjustment (1° to 90°)"
echo "- Import rotation actions from alignmentSlice"
echo "- Fix useCallback dependencies"
echo "- Remove unnecessary React import from AlignmentUI"
echo ""
echo "Note: This is an AI-assist command, not a system command."
echo "The AI should analyze changes and create meaningful commit messages."
